
data:extend({
	{
		type = "autoplace-control",
		name = "starting-lake-size",
		intended_property = "starting-lake-size",
		richness = true,
		order = "z-a",
		category = "terrain",
	},
	{
		type = "autoplace-control",
		name = "starting-lake-regularity",
		intended_property = "starting-lake-regularity",
		richness = true,
		order = "z-b",
		category = "terrain",
	},
	{
		type = "autoplace-control",
		name = "starting-lake-offset-x",
		intended_property = "starting-lake-offset-x",
		richness = true,
		order = "z-c-a",
		category = "terrain",
	},
	{
		type = "autoplace-control",
		name = "starting-lake-offset-y",
		intended_property = "starting-lake-offset-y",
		richness = true,
		order = "z-c-b",
		category = "terrain",
	},
	{
		type = "autoplace-control",
		name = "starting-lake-offset-multiplier",
		intended_property = "starting-lake-offset-multiplier",
		richness = true,
		order = "z-c-c",
		category = "terrain",
	},
	{
		type = "autoplace-control",
		name = "starting-resources-offset-x",
		intended_property = "starting-resources-offset-x",
		richness = true,
		order = "z-d-a",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "starting-resources-offset-y",
		intended_property = "starting-resources-offset-y",
		richness = true,
		order = "z-d-b",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "starting-resources-offset-multiplier",
		intended_property = "starting-resources-offset-multiplier",
		richness = true,
		order = "z-d-c",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "nonstarting-resources-offset-x",
		intended_property = "nonstarting-resources-offset-x",
		richness = true,
		order = "z-e-a",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "nonstarting-resources-offset-y",
		intended_property = "nonstarting-resources-offset-y",
		richness = true,
		order = "z-e-b",
		category = "resource",
	},
	{
		type = "autoplace-control",
		name = "nonstarting-resources-offset-multiplier",
		intended_property = "nonstarting-resources-offset-multiplier",
		richness = true,
		order = "z-e-c",
		category = "resource",
	},
})